@startmindmap

caption Ideation Mindmap
center footer Version 3.0

* (free) rental system

** Donators of hardware
*** Enterprise
*** Individuals

** Funding
*** (Used to) Acquire hardware
*** Government spending
*** Partnerships
*** Advertising

** Terms & Conditions

** Schools/universities
*** Teachers
*** Students
**** Must be eligible
**** State subsidy recipient
***** BAföG
***** Stimulus check
***** Social welfare

@endmindmap
