@startmindmap

caption Teacher Persona
center footer Version 3.0

* Hannelore Schmidt

** Personal
*** 52 Years Old
*** Teacher in the hood
*** Chess and Bocce enjoyer
*** Married to Jürg-Günther, 53, software developer

** "I wish I had the hardware to teach my students in the modern way!"

++ Behaviors
+++ Takes mandatory training courses on highly modern,\rdigital teaching methods.
+++ Lends her husband's old computers to students

++ Wants
+++ Wants her students to succeed in life
+++ Wants to be able to utilize modern, digital teaching methods

@endmindmap
