@startmindmap

caption Parent Persona
center footer Version 3.0

* Sarah Martinez

** Personal
*** 38 Years Old
*** Single parent of four (ages 6 to 16)
*** Education: Limited opportunities for higher education
*** Low-paying job, lives paycheck to paycheck

**: "I wish my kids could have the education I never got to experience.
If only I could afford the cost of hardware and internet with the rising
inflation on the global market, but I can't because of my low-income job!
I can't get a better job because I never got a good education!";

++ Behaviors
+++ Loves and cares for her children
+++ Watches how modern education becomes more digital
+++ Observes the unequal education received by her children

++ Wants
+++ Wants her children to succeed in life
+++ Wants affordable hardware and internet access for \rher children's education

@endmindmap
