@startmindmap

caption Student Persona
center footer Version 3.0

* Josef Persona

** Personal
*** 15 Years Old
*** Student in 10th grade
*** From a lower-class family

** "I wish I could participate in homeschooling, informatics, and gaming!"

++ Behaviors
+++ Attends school
+++ Does not feel comfortable in class
+++ He gets bullied by other students
+++ He is angry at his parents
+++ He plays basketball with his only friend Heinrich
+++ He is interested in computer
+++ He has to go to his friend's house to do his homework
+++ He feels the pressure

++ Wants
+++ To be equal with other students
+++ Access to a laptop
+++ Equality

@endmindmap