@startmindmap

caption Technical Mindmap
center footer Version 3.1

* Technical Aspects

** Orchestration
*** Docker Compose

** Version Control
*** Git
**** Github

** Project Management
*** Agile
**** Scrum
*** Board
**** Trello

** Frontend
*** Vue
*** Bootstrap

** Backend
*** Kotlin
*** Rest API
*** Database
**** Postgres

@endmindmap
